<?php

namespace Webmasterskaya\Unisender\Bitrix\Mail;

use Webmasterskaya\Unisender\Bitrix\APIFactory;

class Mail extends \Bitrix\Main\Mail\Mail implements MailInterface
{
    public static function send($mailParams)
    {
        $result = false;

        $event = new \Bitrix\Main\Event("main", "OnBeforeMailSend", array($mailParams));
        $event->send();
        foreach ($event->getResults() as $eventResult) {
            if ($eventResult->getType() == \Bitrix\Main\EventResult::ERROR) {
                return false;
            }

            $mailParams = array_merge($mailParams, $eventResult->getParameters());
        }

        $mail = static::createInstance($mailParams);
        if ($mail->canSend())
        {
            $api = APIFactory::getInstance();
        }

        return $result;
    }

    public static function createInstance(array $mailParams)
    {
        return parent::createInstance($mailParams); // TODO: Change the autogenerated stub
    }


}